spring:
  profiles:
    # 不同profile配置不同地区shape文件路径
    active: shanghai

# 目标范围，切分矩形大小
# 高德api描述：矩形的左下和右上点坐标，统一以中国为标准，保证计算出的行列号始终一致
extent:
  xmin: 70.0
  xmax: 140.0
  ymin: 3.0
  ymax: 60.0
  width: 5000.0
  height: 5000.0

amap:
  apiKey: bc4831422fb325fed443f7eeaca0fbb5

app:
  kafka:
    brokers: 172.16.233.204:9092,172.16.233.205:9092
    producer:
      topic: t_gdroad_data

---
spring:
  profiles: guangdong

extent:
  folder: guangdong
  description: 广东省
  subFiles:
    - filename: dongguanshi
      name: 东莞市
      innerCode: 1.440000.441900
    - filename: zhongshanshi
      name: 中山市
      innerCode: 1.440000.442000
    - filename: foshanshi
      name: 佛山市
      innerCode: 1.440000.440600
    - filename: guangdongshi
      name: 广州市
      innerCode: 1.440000.440100
    - filename: huizhoushi
      name: 惠州市
      innerCode: 1.440000.441300
    - filename: shenzhenshi
      name: 深圳市
      innerCode: 1.440000.440300
    - filename: zhuhaishi
      name: 珠海市
      innerCode: 1.440000.440400

---
spring:
  profiles: wulumuqi

extent:
  folder: wulumuqi
  description: 乌鲁木齐市
  subFiles:
    - filename: wulumuqishi
      name: 乌鲁木齐市
      innerCode: 1.650000.650100

---
spring:
  profiles: shanghai

extent:
  folder: shanghai
  description: 上海市
  subFiles:
    - filename: shanghaishi
      name: 上海市
      innerCode: 1.310000
